name: onair
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8,<3.13
  - numpy
  - black
  - pylint
  - coverage
  - pytest
  - pytest-mock
  - pytest-randomly
  - pip
  - pip:
    - redis
    - simdkalman
